### ISSUE TITLE
初始化state值是否要在构造函数constructor中进行？

### ISSUE THREAD

**Issue by lihuijuan6060** [reactbdj/reacter#1]
老师，为什么初始化state值时，在Greeting组件中，没有显示声明constructor方法，而且直接初始化state；
而在GreetingInput组件中，是放在constructor方法中进行初始化state？
在网上查到的原话： 
当你在React  class中需要设置state的初始值或者绑定事件时，需要加上constructor(){}

**Comment by bidanjun** [comment]
初始化，在构造函数中是可以的，也可以通过构造函数的参数中传入的属性和context，来更灵活的初始化state。

Greeting组件中的方式，是es7的"类属性"特征，这样初始化也可以。网上查到的，是比较旧的知识，因为class的一些特征，在es6(2015年规范)，当时还没有出现。而"类属性"这个，是在2016年进入js标准的(es2016/2017)

这里也涉及到一个问题，即js最初是脚本语言，没有class，在es6中才有class,但一些特性是受到限制的。Greeting里的写法是较新的标准。
甚至到目前为止，class必备的private/public,js还没有支持。

网络上的资料，搜索的时候，常常会这样，是比较旧的。
所以，这里需要掌握的技巧是，比如对react，若你需要搜索，首先不是通过google，而是先看官网的文档，基本能解决大部分问题。其次github的react项目的issue里面搜索，最后是在stackflow的react标签下搜索。这里都有时间。。。看最新的答案。
若以上三处都无法解惑，则google搜索。。。另外twitter搜索似乎也比较好。

教程里基本上，凡是涉及api变化，不讲解旧的api，而单纯的讲解最新的api，是为了节省大家的时间。关于es2017(最新标准)的class，可以专题的学习一下。
至于网上查到的react class，事实上，react 的class形式的组件，最初是用React.createClass()这样的函数来创建，后来开始，用es6的class，再之后，推荐的做法引入了类属性(上面的写法)、箭头函数+类属性(这样类的函数无需在构造函数中绑定)，这两者都是早先es6不支持的。

如果说清楚了，就关闭issue,没有清晰，继续提问，我尽量的描述清楚。
