### ISSUE TITLE
如何使getelementby方法后于html加载出来

### ISSUE THREAD

**Issue by riugepgf3** [reactbdj/reacter#3]
```
<div>  
          <h1>{` ${this.state.who} `}</h1> 
          <h1>{'白菜'}</h1>
          <button  Id="白菜" value="" onClick={this.switchName()}>{this.state.who===''?'不喜欢':'喜欢'}</button>
          <h1>{'萝卜'}</h1>
          <button Id="萝卜" value=""  onClick={this.switchName()}>{this.state.who===''?'不喜欢':'喜欢'}</button>
          <h1>{'番茄'}</h1>
          <button Id="番茄"  value="" onClick={this.switchName()}>{this.state.who===''?'不喜欢':'喜欢'}</button>
      </div>
      
    `);`
  }
  
   switchName=()=>{
     var like;
    
     var str=document.getElementById('白菜').innerHTML;
     if(str.innerHTML==="喜欢"){
        str.value=1;
        
```

**Comment by bidanjun** [comment]
先得夸一下：有问题立刻提出来，这是聪明人和勇敢的人的行为模式。

1. 企图直接获取html元素，得到当前的值，这是对React的工作机制不了解
    var str=document.getElementById('白菜').innerHTML;
    比如
    <button  Id="白菜" value="" onClick={this.switchName()}>{this.state.who===''?'不喜欢':'喜欢'}</button>
   这里id是不需要的，只需要点击事件
   点击的时候，在onClick里面，使用setState,修改白菜的状态，喜欢或不喜欢。比如这里：白菜对应的"喜欢"状态为true,那么this.state.baicai.like=true....
   setState会导致组件重新绘制，render再次执行，此时将根据新的state值来绘制，由于白菜的喜欢状态现在是true,则按钮的文字应变成"不喜欢"，这是基本的流程。
 
2. this.state.who===''?'不喜欢':'喜欢'。。。这句奇怪，仔细看看三元操作符
    条件？条件成立等于这个:不成立等于这个
3. 如下语句说明对函数变量和执行函数不清楚
    onClick={this.switchName()}> 
    首先，在jsx中，凡是涉及到运算的都要用{},因此，这句并非函数的{},而是jsx的格式。
   那么理解上面的onClick，意思是，onClick等于:执行this.switchName()，这个函数的返回值，就是onClick
   我们再看this.switchName函数，它没有return什么，因此返回值是undefine
   因此这句话的意思是onClick={undefine}

   onClick是button的一个事件，即我们点击了button，则应该执行onClick
   因此我们应该给它赋值，赋值什么？一个函数
  假如你要执行this.switchName这个函数，则应该是onClick={this.switchName}>
  换言之，你传递给它的是一个函数本身，而非这个函数执行完之后的返回值。

请重新阅读greeting最初的教程，那里对于组件、组件的状态和属性，这些描述，应该还没有理解。
react是基于虚拟dom的，我们几乎不会和html页面元素打交道，我们所有的工作，围绕组件、组件的状态、组件的属性等展开。
这也是react连续五年称霸前端的原因之一。
