### ISSUE TITLE
关于函数定义以及setState方法的一些疑问

### ISSUE THREAD

**Issue by Leaf-WXC** [reactbdj/reacter#8]
疑问1.ES6中除了箭头函数并没有其他关于函数定义的语法。ES5中关于函数定义有函数声明和函数表达式两种方式：
方式一：
 FunctionDeclaration :
   function Identifier ( FormalParameterListopt ) { FunctionBody }
方式二：
 FunctionExpression :
   function Identifieropt ( FormalParameterListopt ) { FunctionBody }
在这两种定义方式中都涉及到了function关键字，为什么在我们的教程中可以直接简写为
方式三：
handleChange(event)  { 函数体 }  
这种形式？而不是使用标准的函数定义方法呢？
另外我在其他网站上见到了类似于以下方式的函数定义：
方式四：
函数名 ：function（参数）{ 函数体 }，
这种写法与上面方式三写法等价吗？这四种方式都可以在定义函数时使用吗？
疑问2：
教程中关于setState方法有两种不同的写法，如下：
写法1：
 this.setState((prevState,props)=>({who:'react'})) 
写法2：
 this.setState({who: event.target.value})
那么setState方法的参数可以通过传函数也可以直接把新状态传进去两种方式来改变状态吗？它的参数有没有具体的要求呢？

**Comment by Leaf-WXC** [comment]
查阅React官方文档得知，setState（）定义如下：
setState(updater, [callback])
updater为一个函数：(prevState, props) => stateChange
callback为可选的回调函数。
下面有提到：
您可以随意的传递 一个对象 作为 setState() 的第一个参数，而不是一个函数：
setState(stateChange, [callback])
例如：this.setState({quantity: 2})
那么现在的疑问是：如果两种方式都可行的情况下，
this.setState((prevState,props)=>({who:'react'})) 这种写法的stateChange函数体并没有用到prevState,props这两个参数，可以直接写成：
this.setState(()=>({who:'react'}))    这种形式吗？

**Comment by wxz321123** [comment]
个人理解：关于疑问一  function函数可以 用箭头函数 简写 在Class 里面 如果写function 会报错
 handleChange(event) { 函数体 } 这种形式 在类里面用很常见的形式
this.setState((prevState,props)=>({who:'react'}))
其中的箭头函数 等价于function（prevState,props）{who='react' ；return who;  }
直接写成：
this.setState(()=>({who:'react'})) 这种形式 是可以的 你可以去掉两个参数试一下

**Comment by Leaf-WXC** [comment]
好的，谢谢师兄

**Comment by bidanjun** [comment]
问题： 记住es6或者之后说的es2015,es2016,es2017，这些都是js的补充，为旧版本的js增加一些新的特性。
es6指的是相对旧版js新增的内容
js如何定义函数，es6也是，箭头函数，是定义函数的另一种方式。
箭头函数和普通的函数，区别在箭头函数里的this和普通函数的this不同，搜索es6箭头函数，可以看到很多专题文章，阅读一下就能明白。
js定义函数目前只有两种方式，普通函数定义和现在的箭头函数，列出的多种方式有些就是一样的

问题：关于setState
his.setState((prevState,props)=>({who:'react'}))
这种方式，称为functional setState, 在react官方文档里，从去年开始，推荐使用这种方式。
而只传递一个object的方式是旧的方式
两者存在区别，旧的方式在今后的课程中，禁止使用。
由于大家初学，这部分的区分，暂时不要深入，有一些细节也会忽略。。。事实上，搜索functional setState有很多的文章可看，但现阶段可以不求甚解，以免打击学习的热情
其实只要记住传入函数。。。不传object,它们的区别我们根本无需掌握
